# Generated by Django 5.0.2 on 2024-03-18 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mcdodo", "0002_rename_items_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("order_date", models.DateField()),
                ("payment_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="item_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=9)),
                ("quantity", models.IntegerField()),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mcdodo.item"
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mcdodo.order"
                    ),
                ),
            ],
        ),
    ]
