# Generated by Django 5.0.2 on 2024-04-08 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mcdodo", "0003_order_item_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
