# Generated by Django 5.0.2 on 2024-04-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mcdodo", "0004_alter_order_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_stock",
            field=models.IntegerField(default=0),
        ),
    ]
